import ComplianceScheduleClientPage from "@/components/compliance/ComplianceScheduleClientPage";

export default function ClientComplianceTrainingsPage() {
  return <ComplianceScheduleClientPage category="TRAINING" title="Compliance Trainings" helperText="Download the training PDFs generated by admin and follow the scheduled compliance calendar." />;
}
