import type { Employee } from "@prisma/client";

export type PersonalFilePlaceholder = {
  key: string;
  label: string;
  group: "Client" | "Employee";
};

function formatDate(value: string | null | undefined): string {
  if (!value) return "";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-IN");
}

export const PERSONAL_FILE_PLACEHOLDERS: PersonalFilePlaceholder[] = [
  { key: "client_name", label: "Client Name", group: "Client" },
  { key: "empNo", label: "Employee Number", group: "Employee" },
  { key: "fileNo", label: "File Number", group: "Employee" },
  { key: "pfNo", label: "PF Number", group: "Employee" },
  { key: "uanNo", label: "UAN Number", group: "Employee" },
  { key: "esicNo", label: "ESIC Number", group: "Employee" },
  { key: "firstName", label: "First Name", group: "Employee" },
  { key: "surName", label: "Surname", group: "Employee" },
  { key: "fatherSpouseName", label: "Father / Spouse Name", group: "Employee" },
  { key: "fullName", label: "Full Name", group: "Employee" },
  { key: "employmentStatus", label: "Employment Status", group: "Employee" },
  { key: "designation", label: "Designation", group: "Employee" },
  { key: "currentDept", label: "Current Department", group: "Employee" },
  { key: "salaryWage", label: "Salary / Wage", group: "Employee" },
  { key: "dob", label: "Date of Birth", group: "Employee" },
  { key: "doj", label: "Date of Joining", group: "Employee" },
  { key: "dor", label: "Date of Relieving", group: "Employee" },
  { key: "reasonForExit", label: "Reason for Exit", group: "Employee" },
  { key: "panNo", label: "PAN Number", group: "Employee" },
  { key: "aadharNo", label: "Aadhar Number", group: "Employee" },
  { key: "elcIdNo", label: "ELC ID Number", group: "Employee" },
  { key: "drivingLicenceNo", label: "Driving Licence Number", group: "Employee" },
  { key: "bankAcNo", label: "Bank Account Number", group: "Employee" },
  { key: "ifscCode", label: "IFSC Code", group: "Employee" },
  { key: "bankName", label: "Bank Name", group: "Employee" },
  { key: "mobileNumber", label: "Mobile Number", group: "Employee" },
  { key: "gender", label: "Gender", group: "Employee" },
  { key: "religion", label: "Religion", group: "Employee" },
  { key: "nationality", label: "Nationality", group: "Employee" },
  { key: "typeOfEmployment", label: "Type of Employment", group: "Employee" },
  { key: "maritalStatus", label: "Marital Status", group: "Employee" },
  { key: "educationQualification", label: "Education Qualification", group: "Employee" },
  { key: "experienceInRelevantField", label: "Experience in Relevant Field", group: "Employee" },
  { key: "presentAddress", label: "Present Address", group: "Employee" },
  { key: "permanentAddress", label: "Permanent Address", group: "Employee" },
  { key: "village", label: "Village", group: "Employee" },
  { key: "thana", label: "Thana", group: "Employee" },
  { key: "subDivision", label: "Sub Division", group: "Employee" },
  { key: "postOffice", label: "Post Office", group: "Employee" },
  { key: "district", label: "District", group: "Employee" },
  { key: "state", label: "State", group: "Employee" },
  { key: "pinCode", label: "PIN Code", group: "Employee" },
  { key: "temporaryAddress", label: "Temporary Address", group: "Employee" },
  { key: "nominee1Name", label: "Nominee 1 Name", group: "Employee" },
  { key: "nominee1Relation", label: "Nominee 1 Relation", group: "Employee" },
  { key: "nominee1BirthDate", label: "Nominee 1 Birth Date", group: "Employee" },
  { key: "nominee1Age", label: "Nominee 1 Age", group: "Employee" },
  { key: "nominee1Proportion", label: "Nominee 1 Proportion", group: "Employee" },
  { key: "nominee2Name", label: "Nominee 2 Name", group: "Employee" },
  { key: "nominee2Relation", label: "Nominee 2 Relation", group: "Employee" },
  { key: "nominee2BirthDate", label: "Nominee 2 Birth Date", group: "Employee" },
  { key: "nominee2Age", label: "Nominee 2 Age", group: "Employee" },
  { key: "nominee2Proportion", label: "Nominee 2 Proportion", group: "Employee" },
  { key: "employee_full_name", label: "Employee Full Name Alias", group: "Employee" },
  { key: "employee_emp_no", label: "Employee Number Alias", group: "Employee" },
  { key: "employee_designation", label: "Employee Designation Alias", group: "Employee" },
  { key: "employee_department", label: "Employee Department Alias", group: "Employee" },
];

export function buildPersonalFileTemplateData(employee: Employee, clientName: string) {
  return {
    client_name: clientName || "",
    empNo: employee.empNo || "",
    fileNo: employee.fileNo || "",
    pfNo: employee.pfNo || "",
    uanNo: employee.uanNo || "",
    esicNo: employee.esicNo || "",
    firstName: employee.firstName || "",
    surName: employee.surName || "",
    fatherSpouseName: employee.fatherSpouseName || "",
    fullName: employee.fullName || "",
    employmentStatus: employee.employmentStatus || "",
    designation: employee.designation || "",
    currentDept: employee.currentDept || "",
    salaryWage: employee.salaryWage || "",
    dob: formatDate(employee.dob),
    doj: formatDate(employee.doj),
    dor: formatDate(employee.dor),
    reasonForExit: employee.reasonForExit || "",
    panNo: employee.panNo || "",
    aadharNo: employee.aadharNo || "",
    elcIdNo: employee.elcIdNo || "",
    drivingLicenceNo: employee.drivingLicenceNo || "",
    bankAcNo: employee.bankAcNo || "",
    ifscCode: employee.ifscCode || "",
    bankName: employee.bankName || "",
    mobileNumber: employee.mobileNumber || "",
    gender: employee.gender || "",
    religion: employee.religion || "",
    nationality: employee.nationality || "",
    typeOfEmployment: employee.typeOfEmployment || "",
    maritalStatus: employee.maritalStatus || "",
    educationQualification: employee.educationQualification || "",
    experienceInRelevantField: employee.experienceInRelevantField || "",
    presentAddress: employee.presentAddress || "",
    permanentAddress: employee.permanentAddress || "",
    village: employee.village || "",
    thana: employee.thana || "",
    subDivision: employee.subDivision || "",
    postOffice: employee.postOffice || "",
    district: employee.district || "",
    state: employee.state || "",
    pinCode: employee.pinCode || "",
    temporaryAddress: employee.temporaryAddress || "",
    nominee1Name: employee.nominee1Name || "",
    nominee1Relation: employee.nominee1Relation || "",
    nominee1BirthDate: formatDate(employee.nominee1BirthDate),
    nominee1Age: employee.nominee1Age || "",
    nominee1Proportion: employee.nominee1Proportion || "",
    nominee2Name: employee.nominee2Name || "",
    nominee2Relation: employee.nominee2Relation || "",
    nominee2BirthDate: formatDate(employee.nominee2BirthDate),
    nominee2Age: employee.nominee2Age || "",
    nominee2Proportion: employee.nominee2Proportion || "",
    employee_full_name: employee.fullName || "",
    employee_emp_no: employee.empNo || "",
    employee_designation: employee.designation || "",
    employee_department: employee.currentDept || "",
  };
}
